import type { Article } from "./types.ts";

/**
 * Fortnightly scan of new built-environment AI research, 16 to 30 August 2026.
 * Every paper here was found and verified through the arXiv API, so titles,
 * authors, IDs and dates are taken from the record rather than a summary.
 */

export const paperArticles4: Article[] = [
  {
    slug: "bimscript-scans-into-editable-bim-material-aware",
    cardHook: {
      lead: "faster decoding per step after the CUDA-graph rewrite",
      counter: "the grid granularity that geometric snapping had to fix",
    },
    domain: "Architecture & Predictive Design",
    title: "Scan to editable model: the paper that made BIM ingestion a language problem",
    dek: "Most scan-to-BIM output is a mesh nobody can edit. BIMScript emits a parametric program that maps one-to-one onto Revit objects, and it labels what each element is made of.",
    date: "2026-08-30",
    readingMinutes: 8,
    metrics: [
      { value: "3.4x", label: "Faster autoregressive decoding" },
      { value: "1.9M", label: "Pseudo-labelled elements" },
      { value: "IFC4", label: "Export validated through add-ins" },
    ],
    keywords: [
      "scan to BIM automation",
      "BIM ingestion AI",
      "point cloud to Revit",
      "material identification BIM",
      "structured scene programs",
      "AEC machine learning Ireland",
    ],
    sourcePaper: {
      title: "BIMScript: Material-Aware Structured Scene Programs for BIM Ingestion",
      authors: "Prakash Kondibhau Naikade, Thomas B. Moeslund, Andreas Moegelmose",
      venue: "arXiv, Aalborg University",
      date: "19 August 2026",
      url: "https://arxiv.org/abs/2608.21447",
    },
    body: [
      { t: "p", text: "Scan a building and you get a point cloud. Convert that point cloud and you usually get a mesh. A mesh is a shape. It is not a wall, it is not load bearing, it is not made of anything, and you cannot open it in Revit and change its height." },
      { t: "p", text: "That gap is why scan-to-BIM is still largely a manual modelling job with a very expensive photograph sitting next to it. This paper attacks the gap by changing what the model outputs." },
      { t: "h", text: "Output a program, not a shape" },
      { t: "p", text: "BIMScript treats reconstruction as writing a parametric command program. Rather than predicting geometry directly, it predicts the sequence of instructions that would create that geometry in an authoring tool. The output is inherently editable because it is a set of commands, not a surface." },
      { t: "p", text: "The commercially important detail is one-to-one command-to-Revit-object mapping, validated through add-ins with IFC4 export. That is the difference between a research artefact and something a coordinator could actually receive." },
      { t: "pull", text: "The output is not a picture of a wall. It is the instruction that makes a wall." },
      { t: "h", text: "It also labels what things are made of" },
      { t: "p", text: "The second contribution matters more than it sounds. The layout language is extended with per-element material and condition attributes, supervised by vision-language-model material passports across 100,000 synthetic scenes and 1.9 million pseudo-labelled elements." },
      { t: "p", text: "Material is the property that unlocks everything downstream. Without it you cannot price the element, cannot calculate its embodied carbon, cannot assess its thermal behaviour and cannot plan its replacement. A geometrically perfect model with no materials answers almost no useful question." },
      {
        t: "viz",
        spec: {
          kind: "compression",
          caption: "Autoregressive decoding cost per step, reported in the paper",
          unit: "milliseconds per step",
          rows: [{ label: "Decode step", before: 6.4, after: 1.9 }],
        },
      },
      { t: "p", text: "The speed work is unglamorous and worth noting anyway. Kernel-launch overhead was eliminated with CUDA-graph decoders, taking a decode step from 6.4 to 1.9 milliseconds, and a grammar-parallel draft-and-verify scheme exploits the fact that the entity schema is deterministic. When you know the grammar of the output, you can guess ahead and check." },
      { t: "h", text: "The 5cm problem" },
      { t: "p", text: "Token grids quantise. The paper reports a 5cm granularity limit, which is fine for a demo and useless for a model anyone will build from. Their fix is a hybrid discrete-continuous decoder head with training-free geometric snapping." },
      { t: "p", text: "Read that as an admission and a solution in the same sentence. Discrete tokens gave them tractability and cost them precision, so they bolted a continuous head on to get the precision back. Anyone building in this space will hit the same wall." },
      { t: "h", text: "What this means for a practice" },
      {
        t: "list",
        items: [
          "Ask what the deliverable is. Scan-to-BIM vendors sell a service. The question that separates them is whether you receive editable parametric objects or a mesh you will remodel by hand.",
          "Materials are the value, not the geometry. If the output has no material attribution, you have bought a shape and will pay someone to add the information that mattered.",
          "Synthetic training data is now normal here. 100,000 synthetic scenes is cheaper than any equivalent real capture programme, and it is why this area is moving quickly.",
          "Precision claims deserve a follow-up question. Ask what the underlying grid resolution is before anyone quotes you a tolerance.",
        ],
      },
      { t: "note", text: "How to read this piece: I found this paper through the arXiv API and the title, authors, identifier, date and abstract are taken directly from that record. The figures quoted are the paper's own from its abstract. I have not run the system, and the results are on synthetic scans rather than a real survey, which is exactly the caveat that matters for anyone considering it on a live project." },
    ],
  },

  {
    slug: "safety-certified-reinforcement-learning-building-controls",
    cardHook: {
      lead: "fewer comfort violations than rule-based control",
      counter: "energy saved by the alternative agent",
    },
    domain: "Real Estate & Development",
    title: "Proving an agent will behave: safety certification arrives for building controls",
    dek: "Reinforcement learning has beaten rule-based HVAC control for years. It has never been allowed near a real building, because nobody could guarantee what it would do. This paper certifies it after training.",
    date: "2026-08-30",
    readingMinutes: 8,
    metrics: [
      { value: "67%", label: "Comfort violation reduction, PPO" },
      { value: "27.6%", label: "Energy saving, SAC" },
      { value: "Certified", label: "Constraint satisfaction, post-training" },
    ],
    keywords: [
      "reinforcement learning HVAC",
      "safe AI building controls",
      "building energy optimisation AI",
      "AI governance built environment",
      "EnergyPlus reinforcement learning",
      "smart building AI Ireland",
    ],
    sourcePaper: {
      title: "Safe Deep Reinforcement Learning for Energy-Efficient HVAC Control in Multi-Zone Residential Buildings",
      authors: "Oussama Ziadi, Abdelilah Rochd, Samir Idrissi Kaitouni, Mohamed Oualid Mghazli, Adnane Saoud",
      venue: "arXiv",
      date: "18 August 2026",
      url: "https://arxiv.org/abs/2608.17235",
    },
    body: [
      { t: "p", text: "Reinforcement learning has been beating rule-based HVAC control in simulation for the best part of a decade. Almost none of it has reached a real building." },
      { t: "p", text: "The reason is not performance. It is that a learned policy is a function nobody can read. Ask a facilities manager to hand temperature control of a residential block to a neural network and the first question is not how much energy it saves. It is what happens on the coldest night of the year when the model sees a state it was never trained on." },
      { t: "p", text: "Nobody had a good answer. This paper offers one." },
      { t: "h", text: "Certify after training, not during" },
      { t: "p", text: "Two agents were trained in EnergyPlus through the Sinergym interface, one using Proximal Policy Optimization and one using Soft Actor-Critic, both minimising energy while holding thermal comfort." },
      { t: "p", text: "The contribution is what happens next. Post-training safety certification using Lipschitz-based forward invariance analysis, to guarantee constraint satisfaction. In plain terms: after the agent has finished learning, they prove mathematically that it cannot leave the safe region of operation." },
      { t: "pull", text: "The proof happens after the learning. You do not have to trust the training, only the certificate." },
      {
        t: "viz",
        spec: {
          kind: "stack",
          caption: "Reported results against rule-based control",
          unit: "percent improvement",
          bars: [
            { label: "Comfort violation reduction (PPO)", value: 67, tone: "growth" },
            { label: "Energy saving (SAC)", value: 27.6, tone: "brass" },
          ],
        },
      },
      { t: "p", text: "Note that the two agents won different prizes. PPO cut comfort violations by 67%. SAC saved 27.6% of energy. That is a genuine trade-off rather than a single winner, and it is the trade-off a building owner has to make explicitly rather than discovering after handover." },
      { t: "h", text: "Why this is the more important HVAC paper of the fortnight" },
      { t: "p", text: "There was a second HVAC paper published two days later, ADAPT, which I have written up separately. It posts good numbers on energy and comfort and solves a real deployment problem." },
      { t: "p", text: "This one solves a procurement problem, and procurement is where building AI actually dies. A 27.6% saving does not get you past a risk committee. A guarantee might." },
      { t: "h", text: "What to ask a vendor" },
      {
        t: "list",
        items: [
          "What are the constraints, stated formally? Not what the system tries to do. What it is provably prevented from doing.",
          "Is the guarantee on the trained policy, or on the training process? Only the first survives contact with a state the model never saw.",
          "What happens when a sensor fails? Certification assumes the observations are real, and a stuck thermistor is outside that assumption.",
          "Who signs off? Every credible result in this literature keeps a person accountable. The certificate reduces the risk, it does not transfer the liability.",
        ],
      },
      { t: "note", text: "How to read this piece: found through the arXiv API, with title, authors, identifier, date and results taken from that record. This is simulation work in EnergyPlus on multi-zone residential buildings, not a field deployment, and residential zoning behaves very differently from a commercial office or a mixed-use scheme. Treat the percentages as directional." },
    ],
  },

  {
    slug: "adapt-hvac-control-without-a-calibrated-building-model",
    cardHook: {
      lead: "less HVAC energy without knowing the building geometry",
      counter: "less occupant discomfort at the same time",
    },
    domain: "Real Estate & Development",
    title: "Controlling a building you have no model of",
    dek: "Every predictive HVAC system so far has needed a calibrated thermal model, which is why almost no existing building has one. ADAPT learns the physics instead of being told it.",
    date: "2026-08-30",
    readingMinutes: 7,
    metrics: [
      { value: "7.3%", label: "HVAC energy reduction" },
      { value: "30.2%", label: "Discomfort reduction" },
      { value: "0", label: "Calibrated thermal parameters needed" },
    ],
    keywords: [
      "predictive HVAC control AI",
      "diffusion model building control",
      "building retrofit AI",
      "thermal model free control",
      "existing building stock AI",
      "energy management Ireland UK",
    ],
    sourcePaper: {
      title: "ADAPT: Physics-Aware Diffusion-based World Models for Adaptive Predictive Transferable HVAC Control",
      authors: "Xu Yang, Kailai Sun, Dianyu Zhong, Qianchuan Zhao",
      venue: "arXiv",
      date: "20 August 2026",
      url: "https://arxiv.org/abs/2608.19804",
    },
    body: [
      { t: "p", text: "Predictive control for heating and cooling works. It has worked for years. The catch has always been the prerequisite: you need a calibrated thermal model of the building, and calibrating one is a specialist exercise costing real money on a building that already exists and was never documented properly." },
      { t: "p", text: "That prerequisite is why this technology has landed almost exclusively on new prestige buildings, and why the enormous existing stock that actually needs the savings has been left alone." },
      { t: "h", text: "Learn the physics rather than being handed it" },
      { t: "p", text: "ADAPT is a physics-aware conditional diffusion model that predicts indoor environmental conditions. Instead of consuming a thermal model, it enforces building thermodynamics through a learnable multi-zone heat-balance regulariser." },
      { t: "p", text: "The consequence, stated plainly in the paper, is that it works without known geometry or calibrated thermal parameters. You do not have to survey the building before you can control it." },
      { t: "pull", text: "The prerequisite was never the technology. It was the paperwork about the building that nobody kept." },
      {
        t: "viz",
        spec: {
          kind: "stack",
          caption: "Reported improvement over state-of-the-art baselines",
          unit: "percent reduction",
          bars: [
            { label: "Occupant discomfort", value: 30.2, tone: "growth" },
            { label: "HVAC energy consumption", value: 7.3, tone: "brass" },
          ],
        },
      },
      { t: "p", text: "Read the two bars in the right order. The energy figure is modest. The comfort figure is large, and comfort complaints are what actually consume a facilities team's week. A system that cuts complaints by nearly a third while saving a little energy is an easier internal sell than the reverse." },
      { t: "h", text: "Transferability is the commercial claim" },
      { t: "p", text: "The paper reports robust performance across unseen seasons and climate regions. That word transferable in the title is doing the commercial work, because it is the difference between a bespoke engagement per building and something you can roll across a portfolio." },
      { t: "p", text: "For an Irish or UK asset manager holding thirty mixed-age buildings, that distinction decides whether the business case exists at all. Per-building calibration kills portfolio economics. Transferable models create them." },
      { t: "h", text: "The honest limits" },
      { t: "p", text: "This is simulation work. Simulated buildings are better behaved than real ones: sensors do not drift, occupancy follows a schedule, and nobody props a fire door open in February. The gap between a simulation platform and a 1970s office block in Dublin is the entire risk of the project." },
      { t: "p", text: "Pair it with the safety certification work published two days earlier, which I have written up separately. ADAPT answers whether you can control a building you have not modelled. That one answers whether you should be allowed to." },
      { t: "note", text: "How to read this piece: found through the arXiv API, with title, authors, identifier, date and the two percentages taken from that record. Evaluated on simulation platforms rather than occupied buildings. I have not run the system." },
    ],
  },

  {
    slug: "land-use-transport-building-energy-co-simulation-chicago",
    cardHook: {
      lead: "fall in vehicle miles travelled by 2045 under telecommuting",
      counter: "rise in building energy use over the same period",
    },
    domain: "Architecture & Predictive Design",
    title: "Working from home cut driving by 12.5% and pushed the energy into the buildings",
    dek: "The first platform to model land use, transport and building energy together. It found the thing that separate models cannot: emissions moving from one sector to another rather than disappearing.",
    date: "2026-08-30",
    readingMinutes: 8,
    metrics: [
      { value: "-12.5%", label: "Vehicle miles travelled by 2045" },
      { value: "+1%", label: "Building energy use" },
      { value: "3 models", label: "Coupled into one workflow" },
    ],
    keywords: [
      "urban energy modelling",
      "land use transport building energy",
      "co-simulation planning AI",
      "net zero policy modelling",
      "development planning simulation",
      "urban digital twin Ireland",
    ],
    sourcePaper: {
      title: "A Co-Simulation Platform Coupling Land Use, Transportation, and Building Energy: Development and Case Study",
      authors: "Gopindra Sivakumar Nair, Yilin Jiang, Samuel Maurer, James Cook, Nazmul Arefin Khan, Joshua A. Auld, Tianzhen Hong, Arezoo Besharati, Paul Waddell",
      venue: "arXiv, includes Lawrence Berkeley National Laboratory",
      date: "25 August 2026",
      url: "https://arxiv.org/abs/2608.24817",
    },
    body: [
      { t: "p", text: "Three professions model the same city and never speak. Planners model land use. Transport engineers model movement. Building physicists model energy. Each treats the other two as fixed assumptions." },
      { t: "p", text: "This paper couples them. UrbanSim for land use, POLARIS agent-based transportation, and CityBES for building energy, running as one workflow. The authors describe it as the first platform to integrate all three simultaneously." },
      { t: "h", text: "The result that only a coupled model can produce" },
      { t: "p", text: "Forecasting Chicago to 2045 under several policy scenarios, telecommuting decentralised activity toward outlying areas and cut vehicle miles travelled by 12.5%. Building energy use rose by roughly 1%." },
      {
        t: "viz",
        spec: {
          kind: "stack",
          caption: "Chicago 2045 telecommuting scenario, as reported",
          unit: "percent change",
          bars: [
            { label: "Vehicle miles travelled", value: -12.5, tone: "growth" },
            { label: "Building energy use", value: 1, tone: "clay" },
          ],
        },
      },
      { t: "p", text: "A transport model on its own reports a 12.5% win and stops. A building energy model on its own reports a 1% loss and stops. Neither can see that these are the same people, doing the same activity, in a different place." },
      { t: "pull", text: "The emissions did not disappear. They moved indoors, and only a coupled model can watch them move." },
      { t: "p", text: "The second-order finding is arguably bigger than either number: telecommuting decentralised activity toward outlying areas. Working from home is not only a transport intervention. It is a land use intervention, and it changes where demand for housing and services appears." },
      { t: "h", text: "Why this matters in Ireland and the UK" },
      { t: "p", text: "Both jurisdictions have statutory carbon budgets that are sectoral. Transport has a target. The built environment has a target. Different departments own them." },
      { t: "p", text: "A policy that moves emissions from transport into buildings is a success in one column and a failure in another, and nobody is scored on the sum. This platform makes the transfer visible, which is uncomfortable and useful in equal measure." },
      { t: "p", text: "For anyone doing development appraisal, there is a narrower reading. A scheme in an outlying area justified on transport grounds may carry an operational energy penalty that nobody has priced, and the reverse is equally true." },
      { t: "h", text: "What I would be careful about" },
      {
        t: "list",
        items: [
          "Chicago is not Dublin or Manchester. Grid emissions, building stock age, heating fuel and density all differ enough that the direction may transfer while the magnitude will not.",
          "A 2045 forecast is a scenario, not a prediction. The value is in the relationship between the variables, not the numbers on the end.",
          "Coupling three models means compounding three sets of assumptions. More integrated does not mean more accurate.",
          "The 1% building figure is a system-wide average. The buildings absorbing the shift will see far more than 1%.",
        ],
      },
      { t: "note", text: "How to read this piece: found through the arXiv API, with title, authors, identifier, date and both headline figures taken from that record. I have not accessed the full text or run the platform." },
    ],
  },

  {
    slug: "urbanground-agents-still-get-lost-in-real-cities",
    domain: "Construction Management",
    title: "Agents still get lost: a real-scale city says the hard part is not seeing",
    dek: "A simulation of Hong Kong built from territory-wide 3D geospatial data tested whether AI agents can act in a real built environment. They recognise things well and lose the plot over distance.",
    date: "2026-08-30",
    readingMinutes: 7,
    metrics: [
      { value: "Territory-wide", label: "3D geospatial data, Hong Kong" },
      { value: "Strong", label: "Atomic visual recognition" },
      { value: "Weak", label: "Sustained goal-directed action" },
    ],
    keywords: [
      "multimodal agents built environment",
      "urban navigation AI",
      "agent spatial reasoning",
      "site robotics limitations",
      "autonomous systems construction",
      "AI agent evaluation",
    ],
    sourcePaper: {
      title: "UrbanGround: From Local Perception to Spatial Agency in a Real-Scale City",
      authors: "Tianjie Ju, Zheng Wu, Yueqing Sun, Yuhan Cui, Bobo Li, Shengqiong Wu, Pengzhou Cheng, Haodong Zhao and others",
      venue: "arXiv",
      date: "27 August 2026",
      url: "https://arxiv.org/abs/2608.27456",
    },
    body: [
      { t: "p", text: "Most agent benchmarks are toys. A grid world, a simplified room, a game. This one is Hong Kong, replicated from territory-wide 3D geospatial data, with first-person navigation and spatial reasoning tasks." },
      { t: "p", text: "The question it asks is the one that matters for anything autonomous on a site or in a building: can an agent turn what it sees locally into dependable action across a real, large, messy space?" },
      { t: "h", text: "The answer, and it is a useful no" },
      { t: "p", text: "Contemporary multimodal agents showed useful atomic abilities in visual recognition. They can look at a thing and say what it is. But they struggled with sustained goal-directed urban exploration, and the paper is precise about the failure mode: errors accumulate without effective correction." },
      { t: "pull", text: "It is not that the agent cannot see. It is that it cannot notice it has been wrong for the last twenty minutes." },
      {
        t: "viz",
        spec: {
          kind: "flow",
          steps: [
            { label: "Perceive", detail: "Recognise objects and features in the immediate view. Reported as a genuine strength of current models." },
            { label: "Decide", detail: "Choose the next action from what is visible now. Also broadly works." },
            { label: "Sustain", detail: "Hold the goal across many steps while the scene changes. This is where performance falls away." },
            { label: "Correct", detail: "Notice that the accumulated path has drifted and recover. The reported failure point." },
          ],
          caption: "Where the capability runs out, based on the reported findings",
        },
      },
      { t: "h", text: "Why a negative result is the useful one this fortnight" },
      { t: "p", text: "Four of the five papers I read this fortnight report improvements. This one reports a boundary, and boundaries are what you need when someone is selling you autonomy." },
      { t: "p", text: "The pattern generalises well beyond city navigation. Any agent operating over a long horizon in a physical environment faces the same structure: perception is solved enough, single decisions are fine, and the difficulty is accumulated error nobody catches. That is exactly the failure mode a site robot, an autonomous survey drone or a long-running inspection agent will exhibit." },
      { t: "h", text: "The design implication" },
      {
        t: "list",
        items: [
          "Keep horizons short. Break long autonomous tasks into checkpointed segments where state is verified before the next segment starts.",
          "Build the correction mechanism explicitly. Do not assume the model will notice its own drift, because this paper says it will not.",
          "Evaluate at realistic scale. An agent that works in a demo room tells you nothing about one that works across a floor plate, let alone a site.",
          "Treat perception scores as the easy metric. Recognition accuracy is not evidence of competence at anything sustained.",
        ],
      },
      { t: "note", text: "How to read this piece: found through the arXiv API, with title, authors, identifier and date taken from that record. The characterisation of the findings follows the published abstract; I have not accessed the full text, so the specific task set and scoring are not detailed here. The author list is long and I have named the first eight." },
    ],
  },
];
